SET SCHEMA 'seats';

INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;