SET SCHEMA 'seats_test';

INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;
INSERT INTO seats DEFAULT VALUES;