DROP SCHEMA IF EXISTS seats CASCADE;
CREATE SCHEMA IF NOT EXISTS seats AUTHORIZATION seats;
SET SCHEMA 'seats';

CREATE SCHEMA IF NOT EXISTS seats AUTHORIZATION seats;
CREATE TABLE IF NOT EXISTS seats (id SERIAL PRIMARY KEY, is_occupied boolean DEFAULT false, version integer DEFAULT 1);